name: pr-agent

on:
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write
  issues: write

jobs:
  pr_agent:
    runs-on: ubuntu-latest
    name: Run PR Agent
    if: | 
      github.event.sender.type != 'Bot'
      && github.event.issue.pull_request
      && (
        startsWith(github.event.comment.body, '/describe')
        || startsWith(github.event.comment.body, '/review')
        || startsWith(github.event.comment.body, '/improve')
        || startsWith(github.event.comment.body, '/update_changelog')
        || startsWith(github.event.comment.body, '/ask')
        || startsWith(github.event.comment.body, '/similar_issue')
      )
    steps:
      - id: pr-agent
        uses: Codium-ai/pr-agent@main
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_REVIEWER.EXTRA_INSTRUCTIONS: 'Please use Japanese in descriptions.'
          PR_DESCRIPTION.EXTRA_INSTRUCTIONS: 'Please use Japanese in descriptions.'
          PR_DESCRIPTION.PUBLISH_DESCRIPTION_AS_COMMENT: true
          PR_CODE_SUGGESTIONS.EXTRA_INSTRUCTIONS: 'Please use Japanese in descriptions.'
